API_BASE = 'http://localhost:3000/api'
AUTH_COOKIE_NAME = 'd-session'
USER_AUTH_COOKIE = {
    AUTH_COOKIE_NAME: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDZkZmM3NzM2OWU3YmZmOTI1NGZhZCIsInUiOiJib29tIiwiaXNVc2VyIjp0cnVlLCJpYXQiOjE3MTMxODQxMTMsImV4cCI6MTcxMzI3MDUxM30.NQn_EKmQrweEol8Y5SdsEGPCK1YKbAFNkM4qgfEXe2c'
}
